import re

CHUNK_NAME_FORMAT = re.compile(r'^(\d+)-.*-part\d+\.md$')
MAX_ARTICLES_IN_DEVELOPMENT=100
BATCH_SIZE = 500
CHUNK_BODY_TOKENS = 800
MAX_CHUNK_TOKENS = CHUNK_BODY_TOKENS + 200
OVERLAP_PERCENTAGE = 0.1